- README.md
- src/autoadvance.js
- src/playlist-maker.js
- test/autoadvance-test.js
- test/player-proxy.js
- test/playlist-maker-test.js
This PR does several things:
* autoadvance timeout is now in seconds and not milliseconds
* `autoadvance` is reset whenever a non-playlist item is loaded
* `currentIndex` is set to -1 when a non-playlist item is loaded
* trigger `playlistchange` when the playlist is changed
> timeout, currentIndex -1, playlistchange

- README.md
Auto advance already takes seconds, I'm fixing the README to communicate that.
Closes #2
> Fix README, auto advance takes seconds

- src/playlist-maker.js
- test/playlist-maker-test.js
This fix is for situations where a catalog video contains a source object that does not contain a src property (some videos have a rtmp source). 
From
https://github.com/brightcove/videojs-playlist/blob/master/src/playlist-maker.js#L16
`source.src === src` evaluates to `undefined === undefined` and gives a false match.
I believe this issue is related to BC-35235
> indexOf fix

- README.md
Examples for use of `currentItem()` method misspelled current. Added the T back in where it's needed. This only affects README.md.
> Fixes typos in examples for currentItem() method

- src/play-item.js
- test/play-item.test.js
This PR is to support a list of cue points as a property of a playlist item.
> Support turning a list of cue points into a TextTrack

- src/play-item.js
Fixes #26 . Requires ES5 `Function.prototype.bind` or polyfill.
> Bind `addRemoteTextTrack` to player instance

- src/play-item.js
This PR is to fix up some things from #24. Another BC plugin adds cue points then tracks to a player so this fix is to have consistent textTracks() ordering.
> Add tracks after cue points

- src/play-item.js
- test/play-item.test.js
This PR is for avoiding zero length cuepoint errors.
We are adding a small time to the endTime of a cuepoint, so that zero length cues(same startTime and endTime cues) do not throw out errors.
> Fix for zero length cuepoints

- src/play-item.js
- test/play-item.test.js
Changing the sequence of how we are adding in the endTime , because we always want to have endTime evaluated first even when we have the property time.
> Changing the sequence of properties on OR expression

- package.json
* Fixes #36.
* Only apply browserify-shim when building the dist files.
* Only have `global` be in `dependencies` and not also in `devDependencies`.
> Browserify shim

- docs/api.md
- src/playlist-maker.js
- src/plugin.js
- test/playlist-maker.test.js
Allows the starting index of a playlist to be specified to load a video other than [0] into the player, or no video.
Use cases:
- Playlists that should start on a "featured" item which is not first in the list
- Facilitates direct linking
- Playlists that do not include the content currently playing, e.g. related videos
- Loaded new playlists without interrupting currently playback, e.g. a category tabs UI 
Example: http://jsbin.com/diyove/edit?html,output
`playlist()` takes an additional Number argument for the starting index, defaulting to 0 if not specified. When the playlist is loaded `currentItem()` is used instead of `first()`. An index of `-1` results in playlist loaded but no video from the playlist loaded into the player.
> Load playlist with initial video at specified index or no starting video

- docs/api.md
- package.json
- src/play-item.js
- src/playlist-maker.js
- test/play-item.test.js
- test/player-proxy-maker.js
- test/playlist-maker.test.js
Even though this was an undocumented "feature" of this plugin, we should consider this a major-level change because it _is_ backward-incompatible.
Also, this adds two new events: `"beforeplaylistitem"` and `"playlistitem"`. Our internal code can hook into these to do the work that was previously done here.
> Remove Brightcove VideoCloud-specific Code

- index.html
- package-lock.json
- package.json
- scripts/modules.rollup.config.js
- scripts/test.rollup.config.js
- scripts/umd.rollup.config.js
- src/play-item.js
- test/player-proxy-maker.js
Part of the improvements in Video.js 6 made it so that setting a source is asynchronous. Due to this change, calling `play()` synchronously after `src()` will fail; so, we need to wait for the player to be ready, which is a signal that it can begin playback again.
>  fix: Fix item switching for asynchronous source setting in Video.js 6.

- package-lock.json
- src/auto-advance.js
- test/auto-advance.test.js
When given a auto-advance greater than zero, if a user attempts to begin playback again, the plugin still triggers the auto-advance after the expected number of seconds. So, playback would be interrupted if they wanted to re-watch a source.
Clear the auto-advance timer on the `play` event.
> fix: Fix an issue where we could auto-advance even if the user restarted playback after an ended event.

- src/playlist-maker.js
- test/playlist-maker.test.js
Allow shuffling only the playlist items after the current one.
> feat: Add 'rest' option to the shuffle method.

- docs/api.md
- index.html
- src/playlist-maker.js
- test/playlist-maker.test.js
I realized after merging #92 that the event did not fire on the initial call to `playlist()`. Now, it will fire on the initial call, but `playlistchange` will _not_ fire for backward compatibility.
- `duringplaylistchange` will always fire.
- `playlistchange` will not fire the first time `playlist()` is call (backward compatibility).
- In v5.0.0, `playlistchange` will always fire.
> ignore: Tweak and clarify the firing of 'duringplaylistchange' and 'playlistchange' events.

- package-lock.json
- src/play-item.js
On Safari and Chrome  a promise for `play()` throws an `AbortError DOMException` error if a `pause()` occurs before playback starts. No impact on player functionality but logs an annoying error to the console.
Just catch the exception and do nothing.
- [x ] Feature implemented / Bug fixed
> silence play promise exception

- src/play-item.js
- src/playlist-maker.js
- test/current-item.test.js
- test/player-proxy-maker.js
- test/playlist-maker.test.js
- test/util.js
Fixes #142 
This fixes a regression introduced in #115. The core issue was that we lost the old behavior of falling back to detecting the current item based on its source URL and relied exclusively on the new, internal `playlistItemId_`.
The reported issue (#142) indicated that the `currentItem()` return value before a source was set was now `-1` where previously it was `0`. This is a consequence of that change and has been fixed.
Other issues were discovered in this process. In some cases, we were leaking the internal representation of playlists. Most importantly, though, was the realization that the plugin no longer behaved correctly when a source was set from outside the playlist API (e.g. via `player.src()`).
> fix: Fix regression(s) introduced by changes to the currentItem function in 4.3.0

- package-lock.json
- package.json
- test/playlist-maker.test.js
This updates the default [browserslist](https://github.com/videojs/babel-config/blob/main/es.js#L6-L19) used by babel. It drops support for some older browsers including IE 11. This also removes the `browserslist` in package.json so we use the default list from @videojs/babel-config (linked above), as well as `jsdoc` which was unused and pointing at a defunct repo.
The plan is to merge this into a new `main` branch and do a major version release.
> chore: Update generate-rollup-config to drop older browser support

- .nvmrc
- .whitesource
- docs/api.md
- src/playlist-maker.js
- test/playlist-maker.test.js
This was a feature request from a Brightcove customer: the ability to add or remove single items from the playlist without replacing the entire playlist. Seemed like an easy update and one that would be sensible to make!
* New `add` function for adding playlist items
* New `remove` function for removing playlist items
* Simplified logic for preparing playlist items so that the `add` and `remove` methods could be added with minimal code duplication
* Updated some metafiles
> feat: add `add` and `remove` methods to modify the playlist dynamically

- src/playlist-plugin.js
Inorder to avoid poster flashes in between videos, poster images are hidden in playlists for all but the first video. But since we expect poster images to be displayed for all audioOnly videos, this PR fixes that.
> fix: show poster for audioPosterMode playlist
